### PR TITLE
don't fail on chmod in init.sh

### PR DESCRIPTION
**Pull request by paskal**
That addresses https://github.com/umputun/remark42/issues/1007:
in case of problems we'll have an error on the next line anyway.

### CODE REVIEW

**Review by umputun — COMMENTED** [review]
is it even make sense? in what case allowing chmod to fail will help? maybe if init.sh made +x before? Anyway, have you checked if it helps to address the original issue, i.e. running rootless?

**Comment by paskal** [comment]
I've just tested and it does work even before the change, the only difference is the lack of `chmod: /srv/init.sh: Operation not permitted` message on start. @schnerring do the container fails completely for you after you set the user? Can you please test that PR and tell us if it fixes the problem for you?

**Comment by schnerring** [comment]
I'd be happy to. Could you provide me with a Docker image to test with? I don't have a workstation that's capable of building Docker images right now.

**Comment by paskal** [comment]
@schnerring please check `umputun/remark42:master` not earlier than an hour after this message (to make sure it would be updated from the current master).

**Comment by paskal** [comment]
Closing this PR as it won't solve the issue, remark42 change (https://github.com/umputun/remark42/pull/1017) likely will.

**Comment by schnerring** [comment]
> 
> 
> Closing this PR as it won't solve the issue, remark42 change ([umputun/remark42#1017](https://github.com/umputun/remark42/pull/1017)) likely will.

So I don't need to test? Or am I getting that wrong?

**Comment by paskal** [comment]
You need to test it, but the fix was merged in remark42 and not here.

**Comment by schnerring** [comment]
Running on the latest `master` image (digest `a36fe005e912`), I observe the following error when running the image with UID `1001` and GID `1001`:

```text
execute /srv/init.sh
prepare environment
./web/pl.js
./web/fr.mjs
./web/bg.mjs
./web/index.html
./web/embed.mjs
./web/bp.mjs
./web/bp.js
./web/vi.js
./web/de.js
./web/de.mjs
./web/ua.js
./web/es.mjs
./web/ko.mjs
./web/privacy.html
./web/bg.js
./web/node-emoji.mjs
./web/zh.mjs
./web/ko.js
./web/fi.mjs
./web/markdown-help.html
./web/deleteme.mjs
./web/remark.js
./web/last-comments.js
./web/remark.mjs
./web/tr.mjs
./web/node-emoji.js
./web/ru.js
./web/pl.mjs
./web/counter.mjs
./web/last-comments.html
./web/deleteme.js
./web/embed.js
./web/ja.mjs
./web/zh.js
./web/counter.js
./web/ja.js
./web/es.js
./web/vi.mjs
./web/fr.js
./web/tr.js
./web/ua.mjs
./web/counter.html
./web/ru.mjs
./web/be.js
./web/iframe.html
./web/be.mjs
./web/fi.js
./web/last-comments.mjs
./web/deleteme.html
/srv/init.sh failed
```

**Pull request closed without merging**
